version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    hostname: museum-db
    container_name: museum-db
    volumes:
      - ./start2.sql:/docker-entrypoint-initdb.d/start2.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=museum
      - MYSQL_ADMIN=admin
      - MYSQL_PASSWORD=admin
 
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
    - '8080:80'
    environment:
      PMA_HOST: db 

    
   
  
