version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    hostname: museum-db
    container_name: museum-db
    volumes:
      - ./start.sql:/docker-entrypoint-initdb.d/start.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=museum
      - MYSQL_ADMIN=admin
      - MYSQL_PASSWORD=admin
    ports:
      - '3306:3306'
    networks:
      - museum
 
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
    - '8080:80'
    environment:
      PMA_HOST: db
    networks:
      - museum

  web:
    build: .
    container_name: django-app
    hostname: django-app
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db   
    networks:
      - museum

networks: 
  museum: 
